deploy-0chain/action.yml
Input to set miner fee during 0chain deploy
=> Miner fee input

.github/workflows/manual_system_tests.yml, notify-pull-request/action.yml, run-system-tests/action.yml
This PR adds the following features:
- Supply feature branch instead of docker image, the docker image will be derived by the pipeline automatically 
- A manual system test run will now notify PRs for all components, not just the current repo, so for example if you run manual system tests in 0chain repo, it will now also notify your open PR in blobber repo - this should remove the need for multiple system test runs
- A comment with manual system tests config and result will now be appended to every PR if manual tests are ran
- Extracted manual system tests workflow file to re-useable workflow for easier maintenance 
- Minor bug fixes
=> 0Chain pipeline quality of life improvements

.github/workflows/manual_system_tests.yml
- support to find docker image with `pr-[id]-[8-sha]`
=> fix(manual_system_tests): improved get_tag.sh

deploy-0chain/action.yml
- Adds timeout of 5 minutes to running the blobber-stake script.
=> Add timeout

.github/workflows/manual_system_tests.yml, deploy-0chain/action.yml, run-system-tests/action.yml
- Compares number of restarts before and after system tests execution
- If number of restarts increases then fail the build
- Notify slack channel if system tests fails on master or staging
=> Add network stability check to system tests run + notify slack when system tests fail on staging

.github/workflows/manual_system_tests.yml, deploy-0chain/action.yml
- remove hardcoded branch variable
- remove self hosted label from system tests
=> CI Improvements

deploy-0chain/action.yml
- Adds timeout 300 to second and third retries
- Add logging at end of each failure
=> test logging and timeout

values/test/blobber-values.yaml
-
- fixed https://github.com/0chain/gosdk/issues/463
Tasks to complete before merging PR:
- blobber: https://github.com/0chain/blobber/pull/714
- zwalletcli: https://github.com/0chain/zwalletcli/pull/137
- gosdk:  https://github.com/0chain/gosdk/pull/476
=> fix(token): added QuoteQuery

values/hightps-2/0chain-values.yaml, values/test/0chain-values.yaml, values/test/blobber-values.yaml
-
- remove cct from blobber terms
Tasks to complete before merging PR:
- blobber: https://github.com/0chain/blobber/pull/727
- 0chain: https://github.com/0chain/0chain/pull/1391
- gosdk: https://github.com/0chain/gosdk/pull/494
- system_test: https://github.com/0chain/system_test/pull/302
- zboxcli: https://github.com/0chain/zboxcli/pull/265
- zwalletcli: https://github.com/0chain/zwalletcli/pull/147
- actions: https://github.com/0chain/actions/pull/57
=> fix(config): removed challenge_completion_time from blobber terms

values/hightps-2/0chain-values.yaml, values/test/0chain-values.yaml, values/test/blobber-values.yaml
=> Revert "fix(config): removed challenge_completion_time from blobber terms"

.github/workflows/0chain_network.yaml, deploy-0chain/action.yml, run-system-tests/action.yml
- Removes 0proxy as it is deprecated.
=> Remove 0Proxy

values/test/0chain-values.yaml
=> update free storage

run-system-tests/action.yml
=> feature: changed YAML config for API tests

deploy-0chain/action.yml
fix bug where > 6 blobbers will always fail stake stage
=> Fix blobber stake bug

run-system-tests/action.yml
"authorizer" was spelt incorrectly
=> Fix 0chain crash check

.github/workflows/manual_system_tests.yml
Valid run: https://github.com/0chain/gosdk/actions/runs/4036411581/jobs/6938986885
=> Fix missing type param

deploy-0chain/action.yml
Adds opportunity to set custom "ethereum_node_url" param, which is used by 0chain components to perform interactions with Ethereum network
=> Feature: add "ethereum_node_url" param for "deploy-0chain" workflow

.github/workflows/manual_system_tests.yml, deploy-0chain/action.yml, run-system-tests/action.yml
Depends on:
- https://github.com/0chain/0chain/pull/2168
- https://github.com/0chain/gosdk/pull/800
- https://github.com/0chain/zwalletcli/pull/213
- https://github.com/0chain/zboxcli/pull/366
- https://github.com/0chain/0dns/pull/60
- https://github.com/0chain/token_bridge_authserver/pull/51
- https://github.com/0chain/blobber/pull/966
=> Feature: modify workflows to pass "TENDERLY_FORK_ID" organizational secret

deploy-0chain/action.yml
issue - https://github.com/0chain/gosdk/actions/runs/4289662398/jobs/7472934359
=> fix for zs3server

.github/workflows/manual_system_tests.yml, deploy-0chain/action.yml
Depends on:
- https://github.com/0chain/0chain/pull/2190
- https://github.com/0chain/gosdk/pull/820
- https://github.com/0chain/zboxcli/pull/373
- https://github.com/0chain/zwalletcli/pull/218
- https://github.com/0chain/0dns/pull/61
- https://github.com/0chain/token_bridge_authserver/pull/54
- https://github.com/0chain/blobber/pull/980
- https://github.com/0chain/system_test/pull/579
=> Feature: modify workflows to pass "SUBGRAPH_API_URL" organizational secret

deploy-0chain/action.yml
Due runners being on same server, files in /root folder were being accessed concurrently and causing issues. This PR fixes it by making and using files from runner directory rather than /root.
=> Change config dir from /root

.github/workflows/manual_system_tests.yml
Test: https://github.com/0chain/0chain/actions/runs/4369623726/jobs/7643613048
=> Disable ability to skip tests manually

.github/workflows/manual_system_tests.yml
=> Revert "Disable ability to skip tests manually"

deploy-0chain/action.yml, run-system-tests/action.yml, text-to-png/action.yml
- upgrade to azure/setup-helm@v3 to support ubuntu 22.x
- install deps on fresh server
=> upgraded to setup-helm@v3

deploy-0chain/action.yml, run-system-tests/action.yml, text-to-png/action.yml
=> Revert "upgraded to setup-helm@v3"

deploy-0chain/action.yml, run-system-tests/action.yml, text-to-png/action.yml
- `GOCACHE` or `HOME` is required in `go install`. but setup-go doesn't provide any chance to let us set it by `go env -w`. so added `GOCACHE` in $GITHUB_ENV as global variable.
=> fix(setup-go): fixed GOCACHE is missed on actions/setup-go

.github/workflows/manual_system_tests.yml, deploy-0chain/action.yml, run-system-tests/action.yml
- fixed /usr/local/bin/go is not updated properly. https://github.com/0chain/gosdk/actions/runs/4815066784/jobs/8573405971
=> fix(devops): improved setup-go

.github/workflows/manual_system_tests.yml, deploy-0chain/action.yml, run-system-tests/action.yml
system tests pr :https://github.com/0chain/system_test/pull/656
=> Add support for smoke tests

.github/workflows/manual_system_tests.yml
- fixed `s3_migration_cli_branch` is not passed into `run-system-tests` action
=> fix(devops): fixed s3_migration_cli_branch input issue

deploy-0chain/action.yml
=> Revert "Fix: authorizer deployment script"

run-system-tests/action.yml
- improved yarnkpg installation
=> fix(devops): install yarnpkg

deploy-0chain/action.yml
https://0chain.slack.com/archives/C03PRHNTM0X/p1697846910963969
=> Update authorizers secrets action.yml

deploy-0chain/action.yml
added kafka config wrt the peter changes https://github.com//0chain/0chain/blob/kafka_stream_2/docker.local/config/0chain.yaml#L192
=> added kafka config action.yml

deploy-0chain/action.yml
added kafka changes to enable and disable it for single sharder.
=> added kafka related

deploy-0chain/action.yml
For ST zwallet/zbox cli builds
=> Update to Go 1.21

.github/workflows/manual_system_tests.yml
Related PRs:
* https://github.com/0chain/gosdk/pull/1707
* https://github.com/0chain/blobber/pull/1517
* https://github.com/0chain/token_bridge_authserver/pull/161
* https://github.com/0chain/zboxcli/pull/658
* https://github.com/0chain/zwalletcli/pull/409
* https://github.com/0chain/0box/pull/1275
* https://github.com/0chain/0chain/pull/3411
* https://github.com/0chain/0dns/pull/84
=> Fix: removed virtual testnet creation from manual run
